FROM node:22-slim

RUN apt-get update -y && apt-get install -y openssl git

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build

RUN npx prisma generate
RUN npm run proto:generate

ENV PORT=5000
EXPOSE 5000

CMD sh -c 'node dist/app.js'
