include:
    - mongo-compose.yml
services:
    rabbitmq:
        hostname: rabbitmq
        image: rabbitmq:3-management
        ports:
            - 5672:5672
            - 15672:15672
        restart: on-failure
    gateway:
        hostname: gateway
        build:
            context: .
            dockerfile: ./DOCKERFILE
        ports:
            - 8080:8080
        restart: on-failure
        depends_on:
            - mongo1
            - mongo2
            - mongoInit
            - rabbitmq
