FROM node:22-slim

RUN apt-get update -y && apt-get install -y openssl git

WORKDIR /app

COPY package*.json ./

COPY . .

RUN npm ci

RUN npx prisma generate
RUN npm run proto:generate

RUN npm run build

ENV PORT=5000
EXPOSE 5000

CMD sh -c 'node dist/app.js'
