services:
    mongo1:
        hostname: mongo1
        image: gateway-mongo
        ports:
            - 30001:27017
        restart: always
        command: mongod --bind_ip_all --replSet mongo-set --keyFile /etc/mongo-key
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    mongo2:
        hostname: mongo2
        image: gateway-mongo
        ports:
            - 30002:27017
        restart: always
        command: mongod --bind_ip_all --replSet mongo-set --keyFile /etc/mongo-key
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    mongo3:
        hostname: mongo3
        image: gateway-mongo
        ports:
            - 30003:27017
        restart: always
        command: mongod --bind_ip_all --replSet mongo-set --keyFile /etc/mongo-key
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    mongoInit:
        image: gateway-mongo
        restart: on-failure
        depends_on:
            - mongo1
            - mongo2
            - mongo3
        entrypoint: ["/bin/bash", "/scripts/mongodb_rs_init.sh"]
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
