services:
    mongo1:
        hostname: mongo1
        image: gateway-mongo
        ports:
            - 30001:27017
        restart: always
        command: mongod --bind_ip_all --replSet mongo-set --keyFile /etc/mongo-key
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INIT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INIT_PASSWORD}
    mongo2:
        hostname: mongo2
        image: gateway-mongo
        ports:
            - 30002:27017
        restart: always
        command: mongod --bind_ip_all --replSet mongo-set --keyFile /etc/mongo-key
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INIT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INIT_PASSWORD}
    mongoInit:
        image: gateway-mongo
        restart: "no"
        depends_on:
            - mongo1
            - mongo2
        entrypoint: ["/bin/bash", "/scripts/mongodb_rs_init.sh"]
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INIT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INIT_PASSWORD}
            MONGO_USERNAME: ${MONGO_USERNAME}
            MONGO_PASSWORD: ${MONGO_PASSWORD}
            MONGO_DATABASE: ${MONGO_DATABASE}
